### ISSUE TITLE
Players assigned characters arbitrarily

### ISSUE THREAD

**Issue by carsonlloyd** [carsonlloyd/Clueue2020#11]

**Comment by AmmonHepworth** [comment]
Players should be assigned a character through the networking framework. This should all be coordinated through the host, clients should simply be informed of their character

**Comment by rwalker675** [comment]
Part of the initialization.
In the same host block as the distribute cards.
Same if (host) section.

**Comment by stsnyde** [comment]
Looks like this is implemented in the accept_wrapper function already in the main..?
