### ISSUE TITLE
Mandatory starting movement

### ISSUE THREAD

**Issue by carsonlloyd** [carsonlloyd/Clueue2020#17]

**Comment by rwalker675** [comment]
Assigned to Robert.

**Comment by AmmonHepworth** [comment]
Players in the game start in rooms, and move out into a hallway as soon as the game starts. It is possible that we just start people in hallways if we desire

**Comment by AmmonHepworth** [comment]
Add starting squares as roomTypes.

Add to the acceptable moves dictionary to force movement out in one direction and disallow movement in

Make sure players start in the correct starting square
