### ISSUE TITLE
Implement suggestion mechanics

### ISSUE THREAD

**Issue by AmmonHepworth** [carsonlloyd/Clueue2020#36]

**Comment by AmmonHepworth** [comment]
When a player makes a suggestion, the suspect is moved to the suggestion's room.

**Comment by AmmonHepworth** [comment]
Includes implementing the networking between host and clients for suggestions

**Comment by carsonlloyd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement suggestion mechanics](https://trello.com/c/ZAubaeyw/54-implement-suggestion-mechanics)

**Comment by carsonlloyd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement suggestion mechanics](https://trello.com/c/ZAubaeyw/54-implement-suggestion-mechanics)
