### ISSUE TITLE
Board updates - move to Board class?

### ISSUE THREAD

**Issue by carsonlloyd** [carsonlloyd/Clueue2020#41]
https://github.com/carsonlloyd/Clueue2020/blob/9ab5312a884158698107eb11a86bdc2b542b100e/main.py#L192

Should we put these types of messages inside the movePlayer and updatePlayerPos functions, in the Board class? That way they would happen automatically on any move.

**Comment by AmmonHepworth** [comment]
That would probably be a good decision, I support. We can move it into movePlayer if we want

**Comment by carsonlloyd** [comment]
Okay sounds good -- note this would include sending messages from inside the Board class - we're okay with that?
