### ISSUE TITLE
Correct way to get player position?

### ISSUE THREAD

**Issue by carsonlloyd** [carsonlloyd/Clueue2020#42]
https://github.com/carsonlloyd/Clueue2020/blob/9ab5312a884158698107eb11a86bdc2b542b100e/main.py#L192

should we use this ^ or just
`mainBoard.getPlayerRoom(player)`

**Comment by AmmonHepworth** [comment]
I'm confused, is the line you reference not using mainBoard.getPlayerRoom()? Or are you talking about removing the ".getRoomType()"?

**Comment by carsonlloyd** [comment]
I just mean, does
`mainBoard.getPlayerRoom(player)`
return the same thing as 
`mainBoard.getPlayerRoom(player).getRoomType()`
